name: Build MT3DMS

on:
  push:
    branches:
      - main  # 或者你的主分支
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Fortran compiler (gfortran)
        run: sudo apt-get update && sudo apt-get install gfortran

      - name: Replace call ustop('') with stop
        run: sed -i "s/call ustop('')/stop/g" mt3dms5.3.0/src/true-binary/mt_tob5.for

      - name: Compile MT3DMS
        run: |
          cd mt3dms5.3.0/src/true-binary/  # 进入源代码目录
          gfortran *.for -o mt3dms          # 编译所有 .for 文件
          cd ../../../                       # 返回到仓库根目录

      - name: Upload MT3DMS executable (optional)
        uses: actions/upload-artifact@v4
        with:
          name: mt3dms-executable
          path: mt3dms5.3.0/src/true-binary/mt3dms
